11 Apr 2012 15:25:44,614 [main] WARN  ClusteredServersSelector ===> Server 'http://cs-ccr-oas1.cern.ch:80/logging-data-extractor-20110809-2/remoting/' is down or unreachable: Could not access HTTP invoker remote service at [http://cs-ccr-oas1.cern.ch:80/logging-data-extractor-20110809-2/remoting/ClientRequestController-httpinvoker]; nested exception is java.io.IOException: Did not receive successful HTTP response: status code = 500, status message = [Internal Server Error]
11 Apr 2012 15:25:44,615 [main] WARN  ClusteredServersSelector ===> Attempting again (1) in 5 second(s). 
11 Apr 2012 15:25:53,300 [main] WARN  ClusteredServersSelector ===> Server 'http://cs-ccr-oas1.cern.ch:80/logging-data-extractor-20110809-2/remoting/' is down or unreachable: Could not access HTTP invoker remote service at [http://cs-ccr-oas1.cern.ch:80/logging-data-extractor-20110809-2/remoting/ClientRequestController-httpinvoker]; nested exception is java.io.IOException: Did not receive successful HTTP response: status code = 500, status message = [Internal Server Error]
11 Apr 2012 15:25:53,301 [main] WARN  ClusteredServersSelector ===> Attempting again (1) in 5 second(s). 
11 Apr 2012 15:25:58,304 [main] WARN  ClusteredServersSelector ===> Server 'http://cs-ccr-oas1.cern.ch:80/logging-data-extractor-20110809-1/remoting/' is down or unreachable: Could not access HTTP invoker remote service at [http://cs-ccr-oas1.cern.ch:80/logging-data-extractor-20110809-1/remoting/ClientRequestController-httpinvoker]; nested exception is java.io.IOException: Did not receive successful HTTP response: status code = 500, status message = [Internal Server Error]
11 Apr 2012 15:25:58,305 [main] WARN  ClusteredServersSelector ===> Attempting again (2) in 10 second(s). 
11 Apr 2012 15:26:08,311 [main] WARN  ClusteredServersSelector ===> Server 'http://cs-ccr-oas1.cern.ch:80/logging-data-extractor-20110809-2/remoting/' is down or unreachable: Could not access HTTP invoker remote service at [http://cs-ccr-oas1.cern.ch:80/logging-data-extractor-20110809-2/remoting/ClientVariableController-httpinvoker]; nested exception is java.io.IOException: Did not receive successful HTTP response: status code = 500, status message = [Internal Server Error]
11 Apr 2012 15:26:08,311 [main] WARN  ClusteredServersSelector ===> Attempting again (1) in 5 second(s). 
11 Apr 2012 15:26:13,314 [main] WARN  ClusteredServersSelector ===> Server 'http://cs-ccr-oas1.cern.ch:80/logging-data-extractor-20110809-1/remoting/' is down or unreachable: Could not access HTTP invoker remote service at [http://cs-ccr-oas1.cern.ch:80/logging-data-extractor-20110809-1/remoting/ClientVariableController-httpinvoker]; nested exception is java.io.IOException: Did not receive successful HTTP response: status code = 500, status message = [Internal Server Error]
11 Apr 2012 15:26:13,315 [main] WARN  ClusteredServersSelector ===> Attempting again (2) in 10 second(s). 
